# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src\\infra\\postgres\\schemas.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "E:\\h_lab\\rust\\learn_project\\src\\infra\\postgres\\migrations"
